Repository PhrotonX/PlannerCLI, pull requests merged in 2024-12, with the labels that each got.

#2 Add month class
  .gitignore
  Month.cpp
  Month.h
Labels: pull request, resolved

#12 Replace month constants with enumeration within Month class.
  Month.cpp
  Month.h
Labels: pull request, resolved, approved

#13 Phroton/day class
  Day.cpp
  Day.h
Labels: pull request, resolved, approved

#14 Add month::GetMonthID()
  Month.cpp
  Month.h
Labels: pull request, resolved, approved

#15 Update Day class function names
  Day.cpp
  Day.h
Labels: pull request, resolved, approved

#18 Add Year Class
  Year.cpp
  Year.h
Labels: pull request, resolved, approved

#20 Fix compilation issues with Day.cpp, Month.cpp, and Month.h
  Day.cpp
  Month.cpp
  Month.h
Labels: pull request, resolved, approved

#21 Add README.md file.
  README.md
Labels: pull request, resolved, approved

#23 Add FORMAT.h
  FORMAT.h
Labels: pull request, resolved, approved

#26 Phroton/controller handle input
  .gitignore
  Calendar.cpp
  Calendar.h
  CalendarController.cpp
  CalendarController.h
  Controller.h
  Date.cpp
  Date.h
  Day.cpp
  Day.h
  Month.cpp
  Month.h
  Year.cpp
  Year.h
Labels: pull request, resolved, approved

#25 Use Zeller's Congruence Algorithm
  .gitignore
  Calendar.cpp
  Calendar.h
  CalendarController.cpp
  CalendarController.h
  Date.cpp
  Date.h
  Day.cpp
  Day.h
  Month.cpp
  Month.h
  Year.cpp
  Year.h
Labels: pull request, wip, approved

#27 Add Controller::HandleInput()
  CalendarController.cpp
  CalendarController.h
  Controller.h
Labels: pull request, resolved, approved

#30 Display month content within CalendarView
  CalendarController.cpp
  CalendarView.cpp
  CalendarView.h
  Day.cpp
  Day.h
  View.h
Labels: pull request, resolved, approved

#32 Rewrite the code to make it cleaner
  Calendar.cpp
  Calendar.h
  CalendarController.cpp
  CalendarView.cpp
  CalendarView.h
  Controller.h
  Date.cpp
  Date.h
  Day.cpp
  Day.h
  Month.cpp
  Month.h
  Year.cpp
  Year.h
Labels: pull request, resolved, approved

#31 Calendar Controls
  .gitignore
  App.cpp
  Calendar.cpp
  Calendar.h
  CalendarController.cpp
  CalendarView.cpp
  CalendarView.h
  Controller.h
  Date.cpp
  Date.h
  Day.cpp
  Day.h
  FORMAT.h
  Month.cpp
  Month.h
  Year.cpp
  Year.h
Labels: pull request, resolved, approved

#36 Move day-of-the-week related code from Day class into Date class.
  CalendarView.cpp
  Date.cpp
  Date.h
  Day.cpp
  Day.h
Labels: pull request, resolved, approved

#38 Phroton/day of the week
  Calendar.cpp
  CalendarView.cpp
  Date.cpp
  Date.h
  Day.h
  DayOfTheWeek.cpp
  DayOfTheWeek.h
  Month.h
Labels: pull request, resolved, approved

#35 Phroton/day navigation
  .gitignore
  Calendar.cpp
  Calendar.h
  CalendarController.cpp
  CalendarView.cpp
  CalendarView.h
  Controller.h
  Date.cpp
  Date.h
  Day.cpp
  Day.h
  DayOfTheWeek.cpp
  DayOfTheWeek.h
  Month.cpp
  Month.h
  PlannerCLI.sln
  PlannerCLI.vcxproj
  PlannerCLI.vcxproj.filters
  PlannerCLI.vcxproj.user
  Year.cpp
  Year.h
Labels: pull request, resolved, approved

#41 Phroton/button
  Button.cpp
  Button.h
Labels: pull request, resolved, approved

#42 Add List Class
  List.cpp
  List.h
Labels: pull request, resolved, approved

#45 Use std::vector instead of custom Dynamic array,
  EventManager.cpp
  EventManager.h
  List.h
Labels: pull request, resolved, approved

#47 Move several AddEvent-related code into AddEventController.
  AddEventController.cpp
  AddEventController.h
  EventController.cpp
  EventController.h
Labels: pull request, resolved, approved

#48 Phroton/nullable
  Nullable.cpp
  Nullable.h
Labels: pull request, resolved, approved

#49 Add NullEvent class
  NullEvent.cpp
  NullEvent.h
Labels: pull request, resolved, approved

#54 Phroton/event loose coupling
  EventController.cpp
  EventController.h
  EventView.cpp
  EventView.h
Labels: pull request, resolved, approved

#57 Add View::DisplayHelpInfo()
  AddEventController.cpp
  AddEventView.cpp
  AddEventView.h
  CalendarController.cpp
  CalendarView.cpp
  CalendarView.h
  Controller.h
  EditStringView.h
  EditTimeView.cpp
  EditTimeView.h
  EventController.cpp
  EventView.cpp
  EventView.h
  IDialog.h
  InputStringView.h
  SearchEventView.cpp
  SearchEventView.h
  View.h
Labels: pull request, resolved, approved

#56 Phroton/search event
  AddEventController.cpp
  AddEventView.cpp
  AddEventView.h
  App.cpp
  CalendarController.cpp
  CalendarView.cpp
  CalendarView.h
  Controller.h
  Date.cpp
  Date.h
  EditStringView.cpp
  EditStringView.h
  EditTimeView.cpp
  EditTimeView.h
  Event.h
  EventController.cpp
  EventController.h
  EventManager.cpp
  EventManager.h
  EventView.cpp
  EventView.h
  IDialog.h
  InputStringView.cpp
  InputStringView.h
  PlannerCLI.vcxproj
  PlannerCLI.vcxproj.filters
  SearchEventView.cpp
  SearchEventView.h
  View.h
Labels: pull request, resolved, approved

#63 Phroton/event position
  Event.h
  EventController.cpp
  EventController.h
  EventManager.cpp
  EventView.cpp
  EventView.h
  SearchEventView.cpp
  SearchEventView.h
Labels: pull request, resolved, approved

#39 Phroton/event
  AddEventController.cpp
  AddEventController.h
  AddEventView.cpp
  AddEventView.h
  App.cpp
  Button.cpp
  Button.h
  CalendarController.cpp
  CalendarController.h
  CalendarView.cpp
  CalendarView.h
  Color.cpp
  Color.h
  Controller.h
  Date.cpp
  Date.h
  DayOfTheWeek.cpp
  DayOfTheWeek.h
  EditStringView.cpp
  EditStringView.h
  EditTimeView.cpp
  EditTimeView.h
  Event.cpp
  Event.h
  EventController.cpp
  EventController.h
  EventManager.cpp
  EventManager.h
  EventView.cpp
  EventView.h
  IDialog.cpp
  IDialog.h
  InputStringView.cpp
  InputStringView.h
  List.cpp
  List.h
  NullEvent.cpp
  NullEvent.h
  Nullable.cpp
  Nullable.h
  PlannerCLI.vcxproj
  PlannerCLI.vcxproj.filters
  SearchEventView.cpp
  SearchEventView.h
  Time.cpp
  Time.h
  View.cpp
  View.h
Labels: pull request, resolved, approved

#64 Dev: v1.0.0.1 alpha
  AddEventController.cpp
  AddEventController.h
  AddEventView.cpp
  AddEventView.h
  App.cpp
  Button.cpp
  Button.h
  CalendarController.cpp
  CalendarController.h
  CalendarView.cpp
  CalendarView.h
  Color.cpp
  Color.h
  Controller.h
  Date.cpp
  Date.h
  DayOfTheWeek.cpp
  DayOfTheWeek.h
  EditStringView.cpp
  EditStringView.h
  EditTimeView.cpp
  EditTimeView.h
  Event.cpp
  Event.h
  EventController.cpp
  EventController.h
  EventManager.cpp
  EventManager.h
  EventView.cpp
  EventView.h
  IDialog.cpp
  IDialog.h
  InputStringView.cpp
  InputStringView.h
  List.cpp
  List.h
  NullEvent.cpp
  NullEvent.h
  Nullable.cpp
  Nullable.h
  PlannerCLI.vcxproj
  PlannerCLI.vcxproj.filters
  SearchEventView.cpp
  SearchEventView.h
  Time.cpp
  Time.h
  View.cpp
  View.h
Labels: pull request, wip, approved

#69 Phroton/settings
  Settings.cpp
  Settings.h
  SettingsController.cpp
  SettingsController.h
  SettingsView.cpp
  SettingsView.h
Labels: pull request, resolved, approved

#70 Phroton/calendar view loose coupling
  CalendarView.cpp
  CalendarView.h
  DayOfTheWeek.cpp
  DayOfTheWeek.h
Labels: pull request, resolved, approved

#76 Phroton/fix 73
  EventController.cpp
  EventManager.cpp
  EventManager.h
  Month.h
  typeB/ArrayCalendar.cpp
  typeB/ArrayCalendar.h
  typeB/ArrayDay.cpp
  typeB/ArrayMonth.h
Labels: pull request, resolved, approved

#72 Phroton/array calendar event handling
  App.cpp
  CalendarController.cpp
  CalendarController.h
  EventController.cpp
  EventController.h
  EventManager.cpp
  EventManager.h
  Month.h
  typeB/ArrayCalendar.cpp
  typeB/ArrayCalendar.h
  typeB/ArrayDay.cpp
  typeB/ArrayDay.h
  typeB/ArrayMonth.cpp
  typeB/ArrayMonth.h
  typeB/ArrayYear.cpp
  typeB/ArrayYear.h
Labels: pull request, resolved, approved

#68 Phroton/calendar type b
  App.cpp
  App.h
  Calendar.h
  CalendarController.cpp
  CalendarController.h
  CalendarView.cpp
  CalendarView.h
  DayOfTheWeek.cpp
  DayOfTheWeek.h
  EventController.cpp
  EventController.h
  EventManager.cpp
  EventManager.h
  EventView.cpp
  Month.h
  PlannerCLI.vcxproj
  PlannerCLI.vcxproj.filters
  SearchEventView.cpp
  Settings.cpp
  Settings.h
  SettingsController.cpp
  SettingsController.h
  SettingsView.cpp
  SettingsView.h
  main.cpp
  typeB/ArrayCalendar.cpp
  typeB/ArrayCalendar.h
  typeB/ArrayDay.cpp
  typeB/ArrayDay.h
  typeB/ArrayMonth.cpp
  typeB/ArrayMonth.h
  typeB/ArrayYear.cpp
  typeB/ArrayYear.h
Labels: pull request, resolved, approved

#80 General `App` class and CalendarController improvements.
  App.cpp
  App.h
  CalendarController.cpp
Labels: pull request, resolved, approved

#81 Add exit feature
  App.cpp
Labels: pull request, resolved, approved

#87 Help entity
  HelpTip.cpp
  HelpTip.h
Labels: pull request, resolved, approved

#89 Revert "Update help entity"
  help entity
Labels: pull request, resolved, approved

#82 Phroton/save functionality
  .gitignore
  AddEventController.cpp
  AddEventController.h
  App.cpp
  App.h
  Calendar.cpp
  Calendar.h
  CalendarController.cpp
  CalendarController.h
  Controller.h
  Date.cpp
  Event.h
  EventController.cpp
  EventController.h
  EventManager.cpp
  EventManager.h
  Model.h
  Settings.cpp
  Settings.h
  SettingsController.cpp
  SettingsController.h
  Time.cpp
  Time.h
  typeB/ArrayCalendar.cpp
  typeB/ArrayCalendar.h
Labels: pull request, resolved, approved

#96 Phroton/event glance
  CalendarController.cpp
  CalendarView.cpp
  CalendarView.h
  EventController.cpp
  EventController.h
  EventGlanceView.cpp
  EventGlanceView.h
  EventView.cpp
  EventView.h
  PlannerCLI.vcxproj
  PlannerCLI.vcxproj.filters
  SearchEventView.h
Labels: pull request, resolved, approved

#97 Fix excess connecting border on EventGlanceView
  EventGlanceView.cpp
Labels: pull request, resolved, approved

#93 Create ToDoList.h
  ToDoList.h
Labels: pull request, wip, approved

#105 Update ToDoList.h
  ToDoList.h
Labels: pull request, resolved, approved

#103 Update ToDoView.h
  ToDoView.h
Labels: pull request, resolved, approved

#94 Create ToDoView.h
  ToDoView.h
Labels: pull request, wip, under-review

#95 Create ToDoController.h
  ToDoController.h
Labels: pull request, wip, under-review

#108 Phroton/validation
  AddEventController.cpp
  AddEventController.h
  AddEventView.cpp
  Calendar.cpp
  Calendar.h
  Day.h
  EventController.cpp
  EventController.h
  MessageBoxView.cpp
  MessageBoxView.h
  PlannerCLI.vcxproj
  Time.cpp
  Time.h
Labels: pull request, resolved, approved
